spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: mail@gmail.com  # Gmail .
    password: password
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

mail:
  from: mail@gmail.com
